### ISSUE TITLE
Check for write access

### ISSUE THREAD

**Issue by vladkasianenko** [TileDB-Inc/TileDB-Cloud-Py#354]
https://github.com/TileDB-Inc/TileDB-Cloud-Py/blob/fb3004833e49bc856e8df99d5af8aa7ec43366e8/tiledb/cloud/config.py#L24

It tries to create a file, but the app might run in the container with read-only filesystem.

**Comment by thetorpedodog** [comment]
Thanks for reporting this! The fix is now available on PyPI as of `tiledb-cloud` v0.8.1.
