### ISSUE TITLE
Are there any plans to officially support cloudpickle 3+?

### ISSUE THREAD

**Issue by BBC-Esq** [TileDB-Inc/TileDB-Cloud-Py#693]
Currently it says that it's not compatible with cloudpickle 3+ and I was just curious?

**Comment by sgillies** [comment]
Version 0.13.0 is compatible with cloudpickle>=3. See https://github.com/TileDB-Inc/TileDB-Cloud-Py/releases/tag/v0.13.0 for some detail.
